### ISSUE TITLE
Incorrect str->camelize()

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1090]
How to reproduce

``` zephir
string str1 = "some_string";
string str2 = "someString";

echo str1->camelize(), PHP_EOL;
echo str2->camelize(), PHP_EOL;
```

**Actual**

```
SomeString
Somestring
```

**Expected**

```
SomeString
SomeString
```

PHP's workaround

``` php
$string1  = "some_string";
$string2  = "someString";

$camelize = function ($string) {
    return implode('', array_map('ucfirst', explode('_', $string)));
};
echo $camelize($string1), PHP_EOL;
echo $camelize($string2), PHP_EOL;
```

```
SomeString
SomeString
```

**Comment by GavinMcL** [comment]
Hi looks good I'm seeing correct camel case in the getters/setters now for camel case table field names.

I've just noticed the classname (and therefore php file name), is also being created in title case when the table name is camel case - e.g for a table profileAddress, I get Profileaddress.php with a class Profileaddress - can this be fixed in the same issue as I guess it must use similar camelize function?

**Comment by sergeyklay** [comment]
@GavinMcL Create please separated issue at Devtools repo

**Comment by GavinMcL** [comment]
ok thanks
