### ISSUE TITLE
array_unshift & array_push & ... - don't works

### ISSUE THREAD

**Issue by baszczewski** [zephir-lang/zephir#1123]
In my current project some array functions stops working with the new version of Zephir. For example:

``` php
array_push(this->_prefixes[prefix], utf8_encode(baseDir));
```

gives warning: 

```
Warning: Cannot mark complex expression as reference in /www/XXX/XXX/loader.zep on 93 [invalid-reference]
```

and after run, throws error:

```
Parameter 1 to array_push() expected to be a reference, value given
```

C code generated from Zephir:

``` c++
_12$$5 = zephir_fetch_nproperty_this(this_ptr, SL("_prefixes"), PH_NOISY_CC);
zephir_array_fetch(&_13$$5, _12$$5, prefix, PH_NOISY | PH_READONLY, "XXX/loader.zep", 93 TSRMLS_CC);
ZEPHIR_CALL_FUNCTION(&_14$$5, "utf8_encode", &_11, 119, baseDir);
zephir_check_call_status();
ZEPHIR_CALL_FUNCTION(NULL, "array_push", NULL, 120, _13$$5, _14$$5);
zephir_check_call_status();
```

PS
This also affects other scenerio:

``` php
return reset(first->getData());  
```

In this example I can use reset with previously defined variable:

``` php
let values = firt->getData())
return reset(values);
```

but there is no always opportunities for that.

**Comment by mruz** [comment]
@steffengy I see it happens after https://github.com/phalcon/zephir/commit/a131818066ac296acb7e558e6b475cffd6fb5a38

**Comment by steffengy** [comment]
Yeah it's a more general problem, unfortunately not very trivial to fix.

**Comment by baszczewski** [comment]
@steffengy I think we should come back to previous implementation which works. This is critical stuff.

**Comment by steffengy** [comment]
@baszczewski 
master is by no means stable, this bug is unfortunately another limitation of it.
0.9 generally is not as stable as previously. There also is no release for it on github,
so I for now consider it as "experimtal RC" and advise to fallback to 0.8 for code which
doesn't work as expected on 0.9.

Moving backward would also delay fixing this, since there would be no priority on it,
It also would make all 0.9 code incompatible with future 0.9 versions, which leaves another
BC break which is not advisable at this stage.
In an ideal case it will be fixed very soon and some other limitations will be resolved as well.

It also only effect a small portion of cases, array_push for example
is by no means broken in every case.

**Comment by steffengy** [comment]
Nvm, this is not the issue I was thinking about, fixed in master.

**Comment by baszczewski** [comment]
@steffengy Awesome. Thank You. I really appreciate your hard work.

**Comment by sergeyklay** [comment]
:+1:
