### ISSUE TITLE
call to undefined method finfo::__construct()

### ISSUE THREAD

**Issue by hellobbq** [zephir-lang/zephir#1136]
```
let _finfo = new finfo();
```

**Comment by Jeckerson** [comment]
Prior version `8.0` it is not possible to use inside Zephir via object oriented way, only functions.

So instead of
```
let _finfo = new \finfo();
```

use:
```
let _finfo = finfo_open();
```

Here is the commit where it was fixed and only for PHP8.0 version
https://github.com/php/php-src/commit/4836660b9070b9eef0d30b8ba43f8c82dbbded1f#diff-354051e5e002b4657b61e1d23d490a0ab5a876ad30b3faf407e5a35882279575
