### ISSUE TITLE
Global Namespaces ?

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1207]
Is there any way to create classes in global space ?

**Comment by steffengy** [comment]
no there isn't.
it also was a direct design decision, since polluting the global namespace should
be avoided by any cause to prevent things from breaking with newer versions.

We allow global functions since that can be helpful for helper functions like for localization,
but that also shouldn't be used with any function name that might be generic enough
to be used in later versions of PHP.
