### ISSUE TITLE
PHP 7 for(key,value) loop casting key type to string

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1214]
Well it's not get_object_vars() cuz both php7 and zephir return the same value. Well, they return same value BUT there is problem that's why i reopen issue:
For php5 in zephir for such an array:

```
$test = get_object_vars(new Config(['keys' => ['peter']]));
```

```
var key,value;

for key, value in test {
        var_dump(key);
        var_dump(value);
}
```

returns

```
int(0) string(5) "peter"
```

But for php 7 same code returns:

```
string(1) "0" string(5) "peter"
```

And that's why merge don't work here, cuz this if is not working:
https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L238

Not sure if this is zephir related problem or phalcon. On both php 5 and 7 in php user land key is type of string so it's not php problem.

**Comment by steffengy** [comment]
It is not really clear whether the behavior of get_object_vars is the issue or the for loop, could you please clarify?

**Comment by Jurigag** [comment]
I think its for loop problem. Beacause get_object_vars return same thing in all php versions both in zephir and php user land.

**Comment by JCMais** [comment]
What is the status here?

**Comment by Jurigag** [comment]
Yea i wonder too @steffengy @andresgutierrez it's a bug, right ?

**Comment by mruz** [comment]
@Jurigag could you dump test before loop?

``` zep
var_dump(test);
for key, value in test {
    var_dump(key);
    var_dump(value);
}
```

**Comment by Jurigag** [comment]
As i remember before loop types are fine, as in php, it's beacause key is var type, if you will make it as int then it will work as it should be. But in php 5.x it was working fine(right types).

**Comment by mruz** [comment]
I dumped `get_object_vars($config);`

```
php -r "var_dump(get_object_vars(new Phalcon\Config(['keys' => ['peter']])));"
array(1) {
  ["keys"]=>
  object(Phalcon\Config)#2 (1) {
    ["0"]=>
    string(5) "peter"
  }
}
```

So key can't be `integer` here https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L238 and php7 works fine, but I think hash_key is wrongly detected in php5 https://github.com/phalcon/zephir/blob/e904aba279e139f4954def75cff2bfc5db19bcd0/kernels/ZendEngine2/main.h#L378, eg.

``` zep
public static function test()
    {
        var test = ["0": 1, "1": 2];
        var key, value;

        for key, value in test {
            var_dump(key);
        }
    }
```

```
int(0)
int(1)
```

@andresgutierrez numeric strings are casted to long in hash table?

**Comment by Jurigag** [comment]
Yea but it should be integer to make it work. On php 7 there is string returned, on php 5 integer. Maybe it's just not casted on php7.

**Comment by kse300489** [comment]
In php5 and php7 hashTables is diffrent, new hashTable in php7 is one of many reasons why php7 is faster then php5.

**Comment by Jurigag** [comment]
Yea but it looks like ? That numeric string in phalcon php5 are casted to integer, and on phalcon php7 it doesn't that's why this https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L238 doesn't work here.

Not sure how i should call this issue though.

**Comment by mruz** [comment]
I think key shouldn't be casted on php5. 

``` zep
public static function test()
    {
        var test = ["0": 1, "1": 2];
        var key, value;

        for key, value in test {
            var_dump(key);
        }
    }
```

```
int(0)
int(1)
```

Andy, is it intentional behaviour? if the key won't be casted we should fix the tests otherwise they not pass on php5 also.

**Comment by Jurigag** [comment]
Im not sure if it's about tests, more likely phalcon code.

**Comment by mruz** [comment]
Yes, I meant about phalcon code [config.zep#L227](https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L227) and casting after `get_object_vars`, also using non-assoc array in config is rare.

**Comment by steffengy** [comment]
None of the above statements are actually the real issue here.
Surely it's true that the hashtable implementation is quite different, 
but that has really nothing to do with the issue here.

## **property-names cannot be integers**

This is a known fact and also addressed by passing them to `strval` in `offsetSet` there.

## Why did it work?

The only reason it works in PHP5 is because `get_object_vars` uses [`add_assoc_zval`](https://github.com/php/php-src/blob/PHP-5.4.12/Zend/zend_builtin_functions.c#L1020),
which internally uses a [symtable update](https://github.com/php/php-src/blob/PHP-5.4.12/Zend/zend_hash.h#L348).

> For the people unaware of what a symtable in PHP guarantees:
> It basically statically checks if a string is a number and if so converts it to that number, so
> that "5" and 5 are resolved to the same "storage location" in the underlying hashtable.

This behavior actually is the same in [PHP7](https://github.com/php/php-src/blob/b91197c8a3c5689f77255722d7beb0e9786bc432/Zend/zend_hash.h#L324) but doesn't work due to a different implementation of [`get_object_vars`](https://github.com/php/php-src/blob/4cd9cf8257e40c9fcf43ae2b69bb7b453fc3f6ea/Zend/zend_builtin_functions.c#L1271).

## So what is different in PHP7?

We all knew that properties cannot be integers, but PHP7's `get_object_vars` implementation actually profits from it by not passing strings to a symtable_update but a simple hashtable string update, which is actually the appropriate thing to do. 
(if something cannot be numeric, you shouldn't waste time to check if it's numeric right?)

## How to fix it?

a) Do not map arrays to properties in `offsetSet`
b) **check using is_numeric** rather than `typeof x == integer`

And also please look at the code instead of speculating, which some people
then might believe.

**Comment by andresgutierrez** [comment]
We'll use `is_numeric` in Phalcon to fix the issue, thanks!

**Comment by kse300489** [comment]
@steffengy good explanation
