### ISSUE TITLE
Using Phalcon\Cache\Backend\Redis got segmentation fault with latest Phalcon 2.1.x build and PHP7

### ISSUE THREAD

**Issue by petru-csokany** [zephir-lang/zephir#1219]
Hi,

When I try to use Redis cache with latest Phalcon 2.1.x branch and PHP7 I got segmentation fault. When I use master branch and php 5.6 it works perfectly.

```
php index.php
Segmentation fault
```

If I run under debugger:

```
gdb php
run index.php
```

I got this:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe6ce0fd7 in zephir_call_user_function.3436 () from /usr/lib64/php/modules/phalcon
```

**Comment by steffengy** [comment]
this is something that should be filed as a phalcon bug report as long
as there isn't any concrete connection to wrong behavior on zephir's part.
duplicate of #1218

**Comment by petru-csokany** [comment]
I have posted in phalcon before but someone informed me that is a zephir bug and I should post here.

**Comment by steffengy** [comment]
generally that makes sense, but not as long as it isn't clearly linked to what's causing the failure.

**Comment by petru-csokany** [comment]
Ok, I will try to investigate more this issue and come back with detailed infomations. Thank you!

**Comment by Jurigag** [comment]
I thought its zephir problem beacause last call is `zephir_call_user_function`

Write bt after run index.php and copy-paste it on pastebin maybe

@AniaSoft

**Comment by petru-csokany** [comment]
Means that I can post back this problem to phalcon bug report?

**Comment by steffengy** [comment]
It likely is a zephir problem, but the circumstances leading to the crash aren't clear
enough for anyone to analyze why it might happen, so the issue as it is/was
is just incomplete and nobody would be able to figure out what to do to reproduce the crash and deduce why it's crashing.

**Comment by steffengy** [comment]
just link this issue to the issue in phalcon, @andresgutierrez might get around to fixing it when he gets to work on completing PHP7 support for phalcon.

**Comment by Jurigag** [comment]
@steffengy he just have to post whole backtrace using bt and some short script to reproduce the problem but the same code works on php 5, so i guess it's another zephir related problem with php 7 @AniaSoft

**Comment by petru-csokany** [comment]
I have posted the issue in phalcon bug report. I also have posted there the whole backtrace using bt.

**Comment by steffengy** [comment]
@Jurigag generally yes, but anyhow it makes sense to post phalcon specific issues with phalcon, because the people there generally have phalcon and zephir installed and are able to track it down.
I for example only seldomly grab phalcon to figure out why a bug is happening,
that's also why reduced examples of bugs are generally best, because they do not
include any dependency to another project.

**Comment by Jurigag** [comment]
He posted full stack and it's problem with di. Can your post some example code so I can this on debug version? @AniaSoft

**Comment by petru-csokany** [comment]
Seg fault occurs when this code is executed:

```
use Phalcon\Cache\Frontend\Data;
use Phalcon\Cache\Backend\Redis as RedisCache;

$di->set('cache', function () {
    $frontCache = new Data(array(
        "lifetime" => 86400
    ));
    return new RedisCache($frontCache, array(
        'host' => '127.0.0.1',
        'port' => 6379
    ));
});
```

**Comment by Jurigag** [comment]
Also I'm not sure why we should post it on phalcon. Last call it's zephir function, I could possibly create some code in zephir which will produce same stack without using any phalcon classes, it can't be fix in phalcon until using reflection classes etc but that will be workaround and it's need to be fixed in zephir.

**Comment by steffengy** [comment]
@Jurigag 
Strictly speaking it would actually belong to phalcon
because simply you require phalcon to debug and analyze it that way.

Any useful bug report would be reproducible (or atleast descriptive enough)
that you'd be able to fix it without requiring any 3rd-party application.

The only reason when bug reports from phalcon are tolerated is
a) when there are sufficient instructions to reproduce
b) since phalcon and zephir are pretty coupled

Some of the current phalcon bug reports include an initial hint of what might
be causing the problem and some don't.
Generally I'm not really liking such bug reports ending up here,
since in the last few months they tend to get overlooked here and cannot
be really fixed without taking a look at immense phalcon internal cascades.

**Comment by Jurigag** [comment]
So I have to create the code in zephir without using phalcon classes which will produce the same stack and then you could possibly look into it? I don't get it.

**Comment by steffengy** [comment]
@Jurigag
As you might have noticed the crash happens in `zephir_call_user_function`
that alone is not anywhere near useful since that mehtod is literally called by any method or
function call.
The problem with fixing it is figuring out the context in which it actually crashes, which
requires attaching a debugger and analyzing the bug (or steps that lead to the crash).

If you do that with an extensive amount of code like with a whole phalcon framework loaded,
you might end up chasing one ghost after the other since it's just too easy to get lost in a complex
logic cycle than in a simple test program.

In the past when I had more time for bugs like these, I usually also just produced smaller test cases and fixed them and could also directly integrate them into zephir's unit tests, which has the advantage to prevent the same bugs from occurring again.

**Comment by steffengy** [comment]
@Jurigag
just to clarify: That doesn't mean that you have to produce a smaller test case to fix it,
only that it's advisable and that I won't be able to afford time to look into bugs
occurring in complex 3rd-party situations.

**Comment by Jurigag** [comment]
Okay, so there is context why it's happening:

https://github.com/phalcon/cphalcon/issues/11583#issuecomment-200397410

Zephir have problems when creating instance of object when he has class passed as string. This function is called here in phalcon: https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/di.zep#L235

Exactly this line is producing a problem:

```
'.phtml' => 'Phalcon\Mvc\View\Engine\Php'
```

This issue is related to https://github.com/phalcon/zephir/issues/1218 - it's the same problem, i posted there backtrace but it's deeper, don't know why.

The problem is - op didndt provide full bt log and script to reproduce a problem. If you would see it then i guess you would close it beacause it's the same issue i already posted.

Sorry for this misunderstanding, you are doing great job @steffengy

**Comment by andresgutierrez** [comment]
I´ll take a look on this, I think several issues are caused by the same reason

**Comment by Jurigag** [comment]
@andresgutierrez look on the other i posted here too, beacause they can occur in many places too :)
