### ISSUE TITLE
 Allowed memory size of 134217728 bytes exhausted on zephir_eval_php

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1243]
```
PHP_METHOD(yesser_Test, example) {
  char *str = emalloc(25);
  strcpy(str, "<?php echo 'display'; ?>");
  //RETURN_STRINGL(str, 25, 0);

  zephir_eval_php(str, return_value, "/home/yesser/yesser/test.zep:33" TSRMLS_CC);
 }
```

I'm getting fatal error <b>Fatal error</b>: Allowed memory size of 134217728 bytes exhausted at Zend/zendlanguagescanner.l:657 (tried to allocate 656437128 bytes) in <b>Unknown</b> on line <b>0</b><br />

please help to understand, where i'm doing mistake

**Comment by surjit** [comment]
my goal is to execute php script code from string

**Comment by steffengy** [comment]
This also doesn't have anything to do with zephir.
[From within zephir](https://github.com/phalcon/zephir/blob/e904aba279e139f4954def75cff2bfc5db19bcd0/test/evaltest.zep#l7) you can easily eval code.

Still to answer your requestion:
It seems you might not be familiar with C or zephir-internals
but passing a `char *` as `zval *` cannot work and is particular dangerous.

fcall.h:
`zephir_eval_php(zval *str, zval *retval_ptr, char *context)`

**Comment by surjit** [comment]
please give me example, i'm new to c code

**Comment by surjit** [comment]
or how to call exiting evalCode in c

**Comment by steffengy** [comment]
You might've wanted something like
 `ZVAL_STRING(str, "<?php echo 'display'; ?>", 1)`
insteadof the strcpy.

This is really something related to zend internals (and also changes depending on whether you're using PHP 5/7)
If you really want to write PHP-extensions in C (which I do not really understand since you're looking at zephir which is about to ease the process by introducing an intermediate language which is transpiled into C), you'll have a very hard time as a beginner, since knowledge of C is the very basic requirement but an immense knowledge of zend internals pretty much essential.
