### ISSUE TITLE
can php c extension call zephir function ?

### ISSUE THREAD

**Issue by chenyanginchina** [zephir-lang/zephir#1402]
zephir function cann't work in RINT stage, 
we try to call zephir function in c extension in RINT stage,but it cause segmentfault.

the code is like : 
```c
PHP_RINIT_FUNCTION(habo_prober)
{
    zval *function_name;
    zval *retval;
    MAKE_STD_ZVAL(function_name);
    ZVAL_STRING(function_name,"\\ZephirModule\\Function1",1);

    if ( call_user_function_ex(CG(function_table),NULL,function_name,&retval,0,NULL,0,NULL TSRMLS_CC) != SUCCESS){
        zend_error(E_ERROR,"function call failed!");
    }
    return SUCCESS;
}
```

**Comment by sjinks** [comment]
Just to clarify: your extension and Zephir extension are two different extensions, correct?

**Comment by chenyanginchina** [comment]
yes,two different extensions

**Comment by sjinks** [comment]
Could you please make sure that your other extension has a dependency on your Zephir extension (ie, you have `ZEND_MOD_REQUIRED()` in your other extension)?

The most likely issue for the crash is that Zephir extension has not yet completed RINIT call and therefore has not initialized its internal structures; when your other extension calls a Zephir function, it crashes somewhere in `ZEPHIR_MM_GROW()` because Zephir's internal structures have not been initialized yet.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
