### ISSUE TITLE
PHP7 create symbol table

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1403]
Is there any reason why `create_symbol_table` function is not implementend in ZendEngine3? Like all code there is just commented. For example zephir just uses wrong symbol table for example in this issue - https://github.com/phalcon/cphalcon/issues/12648 on php5 just create_symbol_table() before setting variables is enough but what about php7?

**Comment by sjinks** [comment]
As far as I can tell, symbol tables in ZE3 are linked to the execution context, and it is not trivial to replace the existing symbol table with a newly created one.

What I suggest is: because new symbol tables are used mostly to create an isolated scope for `require` and company, we add a new argument to `zephir_require` family:

```c
int zephir_require_ret(zval *return_value_ptr, const char *require_path, zval * symbol_table) ZEPHIR_ATTR_NONNULL1(2);
```

`symbol_table` is supposed to be an `array` or `NULL`; if it is an array, it is used as a symbol table for the `require`'d file.

The issue is that this would introduce a change to Zephir syntax:

`require path, symtable`

or, as an alternative, we can create an optimizer for a function (say, `require_with_symtable($file, $symtable = NULL)`).

What do you guys think?

**Comment by sergeyklay** [comment]
I like the second option for now

**Comment by Jurigag** [comment]
What does this mean? We would need to create some weird empty array or pass view params with this require?

**Comment by sjinks** [comment]
```php
$symtable = ['var1' => 1, 'var2' => true, /* ... */];
require_with_symtable('somefile.php', $symtable);
// somefile.php sees only variables passed in the $symtable as local ones
```

**Comment by Jurigag** [comment]
Oh okay i understand. But then what with calling `$this->xyz` in such file if it's required in some class? Will this still work?

**Comment by sjinks** [comment]
Good question. No idea until I test

**Comment by dreamsxin** [comment]
Set the `scope`, like `op_array->scope = Z_OBJCE_P(object);`

**Comment by steffengy** [comment]
just FYI: 
There is no reason this was not implemented (except being not important enough for the initial port).
And yes it's technically possible (and not really different to how it's done for ZE2).

**Comment by sjinks** [comment]
```c
static zend_array* add_symtable(zend_execute_data* ex)
{
    zend_array* old_table;
    zend_array* symbol_table = (zend_array*)emalloc(sizeof(zend_array));
    zend_hash_init(symbol_table, 0, NULL, ZVAL_PTR_DTOR, 0);
    zend_hash_real_init(symbol_table, 0);

    zend_rebuild_symbol_table();
    zend_detach_symbol_table(ex);
    old_table = ex->symbol_table;
    ex->symbol_table = symbol_table;

    return old_table;
}

static void restore_symtable(zend_execute_data* ex, zend_array* tbl)
{
    zend_hash_destroy(ex->symbol_table);
    efree(ex->symbol_table);
    ex->symbol_table = tbl;
    zend_attach_symbol_table(ex);
    zend_rebuild_symbol_table();
}
```

If `add_symtable` and `del_symtable` are implemented as Zend functions, they will need to use `ex->prev_execute_data` instead of `ex`.

**Comment by sjinks** [comment]
OK, let us move to #1488 to discuss this further.
