### ISSUE TITLE
Missing optimizers

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1449]
- [ ] extract
- [ ] compact
- [x] get_defined_vars
- [ ] parse_str
- [ ] assert
- [x] func_get_args
- [x] func_get_arg
- [x] func_num_args

Source - https://wiki.php.net/rfc/forbid_dynamic_scope_introspection

**Comment by sjinks** [comment]
`get_defined_vars()` is useless in Zephir: since all methods will be compiled to C functions, there is no way for the ZE to get information about variables.

`get_defined_vars()` will return variables defined in the most recent userland function down the call stack.

**Comment by sjinks** [comment]
See 4d5b616c143e45dc7a3b73d952116243b5ed2cdd

**Comment by sjinks** [comment]
For the same reason `compact()` is also useless: there is no local symbol table in Zephir/C functions.

In theory, `compact()` can be implemented in the parser (because only the parser knows the current symbol table) but I am not familiar with the parser good enough to implement this.

`extract()` won't work in Zephir for the very same reason: there is no symbol table, there is nowhere to extract the variables. Moreover, when used on untrusted input, `extract` poses a security risk.

**Comment by sjinks** [comment]
In ZE3 only `assert("string")` is forbidden, but it can be easily replaced with smth like `assert(eval("string"))`. But again, this is not useful in Zephir, because `eval()` won't have access to local variables as there is no symbol table.

**Comment by sjinks** [comment]
`(mb_)parse_str()` with one parameter also does not make sense in Zephir, and poses a security risk.

**Comment by Jurigag** [comment]
Hmmm then i think maybe we could do some optimizers anyway telling that it's not supported in zephir with reason why, cuz maybe it's not so obvious really(like it doesn't have to be dynamic call but still not working).

**Comment by sjinks** [comment]
Throw an exception during compilation?

**Comment by Jurigag** [comment]
Maybe? @sergeyklay what you think?

**Comment by sjinks** [comment]
`get_defined_vars()` implemented in #1452

**Comment by Jurigag** [comment]
Also im not sure, but the same problem exists on ZE2 too, right?

**Comment by sergeyklay** [comment]
In my opinion we can just throw compilation exception during compilation

**Comment by Jurigag** [comment]
Okay then, i agree.
