### ISSUE TITLE
splat operator

### ISSUE THREAD

**Issue by cyberhck** [zephir-lang/zephir#1662]
I can't define (or at least I don't know how) to declare function with splat operator.
consider the following PHP function:
```php
<?php
function load(string $path, string ...$path) {...}
```

is there anyway to do similar in zephir? if I do `...`, zephir throws error.

**Comment by danhunsaker** [comment]
Variadic arguments aren't supported, yet.

**Comment by dschissler** [comment]
Just so that we're clear I think that isn't really an operator when used for variadic arguments in the method signature.  Splat operator would be for inside function code and its probably two separate C codes that need to be written for each.  They are both pretty nice but for me the actual splat operator along with array deconstruction is something that I really miss in PHP when coming from Javascript.

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/938
