### ISSUE TITLE
great software! however... benchmark doesnt make sense

### ISSUE THREAD

**Issue by streetlist** [zephir-lang/zephir#1671]
I've tried memory accessing using zephir (cache rewrite)
also, md5() function... on php7.2

both are slower than php7.2 so i'm wondering what kind of performance gain i should be doing for this.

i did the normal for ( $i .... ) loop over both features above.

can anyone give me what use case is zephir ideal for?

**Comment by danhunsaker** [comment]
Compiled logic is faster than interpreted, so complex logic is generally considerably faster with Zephir.

That said, anything that calls into PHP functions/methods, even if they are provided by other compiled code, has to go through the same access process as the interpreted PHP, which can end up being slightly slower as values are translated between contexts. This is where Optimizers come in. When defined, an Optimizer overrides the call into PHP itself, allowing you to directly call compiled code without passing into and back out of the PHP interpreter (and then back in and out again with the return value). Essentially, an Optimizer takes Zephir code and outputs the corresponding C code, so all you need to do is define an Optimizer for `md5()` that outputs a call into a C function for that calculation, rather than the PHP function. Rerun your benchmarks with that in place, and you should see much better results.

I'd love to take a look at your benchmarks, by the way. Possibly even add them to the actual test suite for Zephir itself.

**Comment by Jurigag** [comment]
Zephir is not faster than php. Doing md5 on php always will be faster than doing md5 on zephir - simply because for example on zephir you need to create class, where on php not.

You need to make sure that you are actually checking result of this md5(like time to do it inside zephir method, not in php code where you do something like:

```php
$x = new ZephirTest();
$startTime = microtime();
for{$i = 0; $i++; $i < 999999) {
    $x->md5();
}
...
```

If you compare code like this to just php alone md5 than you will obviously will end in much worse performance because php needs to call method. To reproduce it fully you should create class in php with proper method and do it the same way like for zephir.

Not sure what's your case, but using zephir just to do md5 is out of any point. Zephir is for writing big extensions with many operations, like for example phalcon framework.

**Comment by danhunsaker** [comment]
This is also true, yeah.
