### ISSUE TITLE
How do you implement an external interface?

### ISSUE THREAD

**Issue by danielspk** [zephir-lang/zephir#1686]
Hi, how can I compile a class that implements an external interface? **( Psr\Http\Server\MiddlewareInterface)**

Compiler show: *"Cannot locate interface Psr\Http\Server\MiddlewareInterface when implementing interfaces on ..."*

Example:

```
namespace App;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class Middleware implements MiddlewareInterface
{
    public function process(<ServerRequestInterface> request, <RequestHandlerInterface> handler) -> <ResponseInterface>
     {
         return handler->handle(request);
     }
}
```

Thanks!

**Comment by sergeyklay** [comment]
I created a PR  (#1687) to show community the approach to use 3rd party extensions as a project dependencies. 

https://travis-ci.org/phalcon/zephir/builds/445511734

/cc @danielspk @niden

**Comment by danhunsaker** [comment]
That works for extensions, but not so much for interfaces otherwise defined in PHP userspace.

Unfortunately, as Zephir is compiled, it can't support implementing or extending interfaces or classes that aren't also available from the C side of things (that is, other extensions). Same goes for traits, for the same reasons. Compiled code can't be partially built from interpreted code.

The fact that compiled code can _call_ interpreted code makes this distinction harder to see, I suspect, but the things an extension calls aren't part of the extension itself, so the distinction is still there.

Hopefully that helps answer your original question, while @sergeyklay's PR should help with your specific use case by providing a workaround.

**Comment by niden** [comment]
We need to add this in the documentation.
