### ISSUE TITLE
Zephir doesn't do anything

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1838]
I try to run zephir but it screams and whine about namespaces all the time. Why can't it just take a zep file and turn it into C? Why is it trying to be composer?

**Comment by joeyhub** [comment]
```
# zephir init --help

Name:
    init -- Initializes a Zephir extension.

Synopsis:
    zephir init [options]

Description:
    The options are as follows:

    namespace                                The extension namespace.
    --backend=ZendEngine2|ZendEngine3        Used backend to create extension.
```

In reality: `zephir init [options] <namespace>`

The namespace is mandatory.

**Comment by sergeyklay** [comment]
It is by design. Initially Zephir _program_ was designed to create/compile/install namespaced projects written in Zephir _language_. Code in Zephir must be placed in classes. The language is intended to create object-oriented libraries/frameworks, so code outside of a class is not allowed. Additionally, a namespace is required.
