### ISSUE TITLE
Massive Overhead eliminates performance gains.

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1845]
It appears zephir lacks the ability to call things internally directly?

If should always make internal C functions then add a layer to expose them to PHP. Instead it seems to call functions internally which delivers a devastating performance hit.

This hit is so extreme that it can cause zephir to perform significantly worse than PHP. It starts out a lot faster when there aren't many function calls in process and then bombs when you need to make lots of calls.

Is there a way around this? What happens if I make a method private? It'll still mess up for interclass coms though!

**Comment by dschissler** [comment]
I've heard rumors about some kind of "fast function calls" research going on.  The people who work on these sorts of things aren't exactly renowned and celebrated for their communication patterns.  If you can fix this stuff then [get in there and get paid](https://opencollective.com/phalcon).  Seriously the money just sits there growing slowly because the people who do the work are working slowly and not collecting and nobody else is interested.  You could practically set yourself up for retirement if you did a bunch of Zephir work.

**Comment by dreamsxin** [comment]
Custom Kernel c code，and use zephir optimizers.

**Comment by CameronHall** [comment]
@joeyhub do you have any examples of this? It's important to remember that Zephir is effectively a php-esque syntax to transpile to C and not a language itself. As such the resulting C code won't _always_ be the most efficient. 

@dreamsxin mentioned Zephir Optimizers and Custom Kernel C code. If you're interested in exploring the out of the box solution, I encourage you to check out the [Zephir Optimizers](https://docs.zephir-lang.com/0.11/en/optimizers). Alternatively, you can always write your own code and modify the kernel (if you're not sure how to do this check out the Phalcon `config.json` file) :)

**Comment by Jurigag** [comment]
Also there is internal keyword as far as i remember which avoids calling through zend engine and calls it on C code.

https://github.com/phalcon/zephir/pull/962
