### ISSUE TITLE
When camelize is double applied, the character string does not become UpperCamelCase(PascalCase)

### ISSUE THREAD

**Issue by fagai** [zephir-lang/zephir#2115]
```php
$text = 'sample_sample';
$text = \Phalcon\Text::camelize($text); // SampleSample
$text = \Phalcon\Text::camelize($text); // Samplesample
```

Can this problem be resolved?

**Comment by AlexNDRmac** [comment]
function camelize using two args: `camelize(text, delimiter)`
In your example, you always overwrite your `$text` variable and it looks not obvious.
```php
$text = 'sample_sample';
$text = \Phalcon\Text::camelize($text); // SampleSample
$text = \Phalcon\Text::camelize($text); // Samplesample

// So, how it looks exactly

$text = 'sample_sample';
// we should get SampleSample, because we have underscore as delimiter
$text = \Phalcon\Text::camelize('sample_sample'); // SampleSample
// we don't have any delimiter, so we should have `Samplesample` as expected result 
$text = \Phalcon\Text::camelize('SampleSample'); // Samplesample
```

**Comment by fagai** [comment]
thank you.

I don't think the output of `\Phalcon\Text::camelize('SampleSample')` is `Samplesample`.
Is this result desired?

**Comment by AlexNDRmac** [comment]
Yes, this result is expected. How function without explicit delimiter should detect proper char to make this char uppercase?

**Comment by chilimatic** [comment]
also it's pascal- not camelcase.

**Comment by fagai** [comment]
oh, pascal case...

Is it supposed that the character string `SamPle` comes in?
I feel that the process of making all lowercase letters once is unnecessary.

**Comment by danhunsaker** [comment]
~~This is how the function works in other frameworks and libraries, too - everything is lowercased unless it follows a delimiter (generally `_`, `-`, or ` `). Partially because of constants - `FOO_BAR` should properly be camelized to `fooBar` or `FooBar`.~~ There's some disagreement about whether the result should be camelCase or UpperCamelCase.

But yeah, these functions aren't designed to have strings passed through more than once, and they expect certain kinds of input. If your input string doesn't have word delimiters in it, you probably don't want to `camelize()` it.
