### ISSUE TITLE
Is there a way to modify config.m4 and config.w32?

### ISSUE THREAD

**Issue by andrewdalpino** [zephir-lang/zephir#2150]
Is there a way to add code to the `config.m4` or `config.w32` files through Zephir? Or, if we add something manually will it ever get overwritten by Zephir? Here's the issue we're facing https://github.com/RubixML/Tensor/pull/11.

Thank you!

**Comment by AlexNDRmac** [comment]
You can add additional flags for compiler with `config.json` as described in [documentation](https://docs.zephir-lang.com/0.12/en/config#extra-cflags)
Any changes (if you add it manually) in `config.m4` and `config.w32` will be overwritten by `zephir generate`

**Comment by andrewdalpino** [comment]
Hi @AlexNDRmac, we are now facing two issues related to this. One of the ideas that we have floating around is to run a patch script as part of our build process. Is there anything in the language (Zephir) besides additional compiler flags that would help us in this situation?

https://github.com/RubixML/Tensor/pull/11

https://github.com/RubixML/Tensor/pull/14

Thank you!

**Comment by AlexNDRmac** [comment]
Hi @andrewdalpino, current version of Zephir does not support template overrides. We will be able to implement this feature in the next version.
As a workaround, I can suggest using the Zephir sources with modified `./templates/ZendEngine3/config.*` files, which you will be able to reuse after implementing the feature with template overriding.

**Comment by andrewdalpino** [comment]
That's pretty sweet! Looking forward to it

I did this for now https://github.com/RubixML/Tensor/blob/master/extension-config-patch.php. It runs after calling our custom `$ composer compile` command.

It looks like we may not need it once we make the switch to the new version of Zephir in the next major release, see https://github.com/RubixML/Tensor/issues/13#issuecomment-785689021.

Thanks again, you guys are the best

**Comment by mlocati** [comment]
The docs say that
- the `generate` command generates the C source code from the zephir source files
- the `compile` command compiles the C source code into the binary extension file(s)
- the `install` command install the binary extension file(s).
- the `build` command is like calling in sequence `generate`, `compile` and `install`

So, if we need to to patch the `config.m4` file, logic suggests that we could adopt this approach:

- use the `generate` command
- patch the `config.m4` file
- use the `compile` command
- use the `install` command

BTW at the moment:

- calling the `compile` command also calls the `generate` command
- calling the `install` command also calls the `compile` command

Which is counter intuitive:

1. calling the `build` command is the same as calling the `install` command (because it calls the `compile` command, and it also calls the `generate` command)
2. we can't do anything (like patching `config.m4`) between the `generate` command and the `compile` command
3. we can't do anything between the `compile` command and the `install` command

**Comment by Jeckerson** [comment]
Related #1733
