### ISSUE TITLE
Error control operator @. Scanner: unknown opcode 64

### ISSUE THREAD

**Issue by valVk** [zephir-lang/zephir#906]
If I use the next code `@unlink("./filename.txt");` than I get the error shown below

Scanner: unknown opcode 64
Zephir\Exception: Cannot parse file: /freespace/sites/phalcon/zephir-projects/twigz/twigz/test.zep

As I understand I have to do something similar to this

``` php
class Test {

    public function testMethod()
    {
        var atunlink;

        let atunlink = "@unlink";

        {atunlink}("./filename.txt");
    }
}

```

Am I correct?

Thanks.

**Comment by andresgutierrez** [comment]
It's probably the @, that operator does not exist in Zephir

**Comment by fezfez** [comment]
How to catch notice/warning then ?

A sample of usefull @ 

```php

$isUnlink = @unlink('file');

if ($isUnlink === false) {
    echo 'Not unlink';
}

// output 
// Not unlink

// Without @


$isUnlink = unlink('file');

if ($isUnlink === false) {
    echo 'Not unlink';
}

// output 
// Warning: unlink('file') [function.unlink]: No such file or directory in ...
// Not unlink

```

**Comment by steffengy** [comment]
In that case it would be clever to first check if the file exists.

It is generally wise not to mute errors of a function, because
you won't notice when it fails for a different reason, than expected, 
which is a pretty good example of bad design.

**Comment by fezfez** [comment]
A sample of good use of '@' https://github.com/symfony/Filesystem/blob/master/Filesystem.php#L95

**Comment by steffengy** [comment]
Ocourse there are possibilities to use it somehow "good", but even that example you point out,
could fail and provide a wrong error in an edge case where an error occurs between the mkdir and error_get_last.

I do not think it is worth the effort implementing this in zephir, 
since it is in my opinion one of PHP's worse features.

You can still check for the success of the statement, without the operator.
The problem of the error being shown to the user is solved by disabling
error output and reducing it to logging only, which is the better design
choice.

**Comment by fezfez** [comment]
Or maybe add exception system like PHP7 ?

**Comment by steffengy** [comment]
Maybe that will solve itself with future version of PHP, which migrate errors/warnings to exceptions,
unfortuntately thats not quite done yet.

**Comment by Jeckerson** [comment]
Use `file_exists()` before `unlink`. Until there is no exception in PHP for this it can't be improved in Zephir. Closing.
